// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj-GNyNfl5_-YnzfiTK132w1laIih7po4',
    appId: '1:342451583132:web:6da607d17c6195e9e9d559',
    messagingSenderId: '342451583132',
    projectId: 'teamduty-17a6e',
    authDomain: 'teamduty-17a6e.firebaseapp.com',
    storageBucket: 'teamduty-17a6e.firebasestorage.app',
    measurementId: 'G-ZY56EJK5B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYgBQVNENpaRl22obwcmqojpfge_H-e9o',
    appId: '1:342451583132:android:e302d4066ba73583e9d559',
    messagingSenderId: '342451583132',
    projectId: 'teamduty-17a6e',
    storageBucket: 'teamduty-17a6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwunKwkYn24_mWhhXdZ4tyXJnVdivPJls',
    appId: '1:342451583132:ios:c2d17c5162571f0be9d559',
    messagingSenderId: '342451583132',
    projectId: 'teamduty-17a6e',
    storageBucket: 'teamduty-17a6e.firebasestorage.app',
    iosBundleId: 'com.example.teamduty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwunKwkYn24_mWhhXdZ4tyXJnVdivPJls',
    appId: '1:342451583132:ios:c2d17c5162571f0be9d559',
    messagingSenderId: '342451583132',
    projectId: 'teamduty-17a6e',
    storageBucket: 'teamduty-17a6e.firebasestorage.app',
    iosBundleId: 'com.example.teamduty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj-GNyNfl5_-YnzfiTK132w1laIih7po4',
    appId: '1:342451583132:web:d1479d44c902cc87e9d559',
    messagingSenderId: '342451583132',
    projectId: 'teamduty-17a6e',
    authDomain: 'teamduty-17a6e.firebaseapp.com',
    storageBucket: 'teamduty-17a6e.firebasestorage.app',
    measurementId: 'G-5LL482EN2L',
  );

}